DOCKERHUB_USERNAME=username

DOCKER_REPOSITORY="index.docker.io/${DOCKERHUB_USERNAME}"
DOCKER_REGISTRY="index.docker.io"
REGISTRY_USERNAME=${DOCKERHUB_USERNAME}
REGISTRY_PASSWORD="password"
CUSTOM_BUILDER_IMAGE="index.docker.io/${DOCKERHUB_USERNAME}/tbs-default-cluster-builder"